### PR TITLE
docs: create start-up cost and conclusion

### PR DESCRIPTION
**Pull request by wiyantoeric**

### CODE REVIEW

**Comment by AlphaByte-RedTeam** [comment]
@wiyantoeric Ric, have you add the "other expenses" and "total start-up cost" in the **Start-Up Costs** table?

**Comment by AlphaByte-RedTeam** [comment]
@wiyantoeric can u also make the table to be center aligned?

**Comment by wiyantoeric** [comment]
> @wiyantoeric Ric, have you add the "other expenses" and "total start-up cost" in the **Start-Up Costs** table?

ow i missed that part, thanks for telling me know. i'll get into it

**Comment by wiyantoeric** [comment]
> @wiyantoeric can u also make the table to be center aligned?

sure

**Review by AlphaByte-RedTeam — APPROVED** [review]

**Comment by AlphaByte-RedTeam** [comment]
LGTM!

**Pull request merged**
